create or replace PROCEDURE LLENAR_BASE
IS
  CURSOR DATOS_TMP IS SELECT * FROM TEMPORAL ORDER BY FECHA ASC;
  DATOS_TABLAS DATOS_TMP%ROWTYPE;
  EXISTE INTEGER;
  ID_TEMPORADA INTEGER;
  ID_JORNADA INTEGER;
  ID_VISITANTE INTEGER;
  ID_LOCAL INTEGER;
  PUNTOS_VICTORIA VARCHAR2(3);
  PUNTOS_EMPATE INTEGER;
  EDICION INTEGER;

  BEGIN

    OPEN DATOS_TMP;
    LOOP
      FETCH DATOS_TMP INTO DATOS_TABLAS;
      EXIT WHEN DATOS_TMP%NOTFOUND;
      --GUARDAMOS ID DE LA TEMPORADA DEL REGISTRO QUE VAMOS A INSERTAR
      SELECT TMP.ID_TEMPORADA INTO ID_TEMPORADA FROM TEMPORADA TMP WHERE TMP.AÑO_INICIO = DATOS_TABLAS.INICIO_ANIO AND TMP.AÑO_FINALIZA = DATOS_TABLAS.FIN_ANIO;
      --GUARDAMOS EL ID DEL EQUIPO LOCAL Y VISITANTE QUE VAMOS A INGRESAR
      SELECT EQ.ID_EQUIPO INTO ID_LOCAL FROM EQUIPO EQ WHERE EQ.NOMBRE_EQUIPO = DATOS_TABLAS.EQUIPOLOCAL;
      DBMS_OUTPUT.PUT_LINE ('ID LOCAL: ' || ID_LOCAL);

      SELECT EQ.ID_EQUIPO INTO ID_VISITANTE FROM EQUIPO EQ WHERE EQ.NOMBRE_EQUIPO = DATOS_TABLAS.VISITANTE;
      DBMS_OUTPUT.PUT_LINE ('ID visitante: ' || ID_VISITANTE);
      --VERIFICAMOS SI EXISTE EL REGISTRO DE LA JORNADA QUE VAMOS A INSERTAR Y SE GUARDA EN LA VARIABLE 'EXISTE'
      SELECT COUNT(J.ID_JORNADA) INTO EXISTE FROM JORNADA J
      WHERE J.NO_JORNADA = DATOS_TABLAS.JORNADA
      AND J.TEMPORADA_ID_TEMPORADA = ID_TEMPORADA;

      /*SI NO EXISTE EL REGISTRO ENTONCES LO CREAMOS*/

      IF EXISTE = 0 THEN
        INSERT INTO JORNADA(NO_JORNADA, TEMPORADA_ID_TEMPORADA)
        VALUES(DATOS_TABLAS.JORNADA, ID_TEMPORADA);
        /*OBTENEMOS EL ID DE LA JORNDADA Y LO GUARDAMOS EN LA VARIABLE 
        ID_JORNADA*/

        SELECT MAX(J.ID_JORNADA) INTO ID_JORNADA  FROM JORNADA J;
      ELSE
        /*OBTENEMOS EL ID DE LA JORNDADA Y LO GUARDAMOS EN LA VARIABLE 
        ID_JORNADA*/
        SELECT J.ID_JORNADA INTO ID_JORNADA FROM JORNADA J
        WHERE J.NO_JORNADA = DATOS_TABLAS.JORNADA
        AND J.TEMPORADA_ID_TEMPORADA = ID_TEMPORADA;
      END IF;

      --DESPUES DE INSERTAR EL DATO COLOCAMOS EXISTE = 0
      EXISTE := 0;
  

      /*OBTENEMOS EL PUNTAJE POR VICTORIA O EMPEATE DEPENDIENDO DE LA TEMPORADA*/

       SELECT TMP.PTS_GANADOR INTO PUNTOS_VICTORIA  FROM temporada TMP WHERE TMP.AÑO_INICIO = DATOS_TABLAS.INICIO_ANIO AND TMP.AÑO_FINALIZA = DATOS_TABLAS.FIN_ANIO;

        
       SELECT TMP.PTS_EMPATE INTO PUNTOS_EMPATE FROM TEMPORADA TMP WHERE TMP.AÑO_INICIO = DATOS_TABLAS.INICIO_ANIO AND TMP.AÑO_FINALIZA = DATOS_TABLAS.FIN_ANIO;

       /*OBTENEMOS LA EDICION DE LA TEMPORADA*/
       SELECT TMP.EDICION INTO EDICION FROM TEMPORADA TMP WHERE TMP.AÑO_INICIO = DATOS_TABLAS.INICIO_ANIO AND TMP.AÑO_FINALIZA = DATOS_TABLAS.FIN_ANIO;
        DBMS_OUTPUT.PUT_LINE ('EDICION ' || EDICION);
      /*BUSCAMOS EL REGISTRO DEL PARTIDO Y SI EXISTE O NO, LO GUARDAMOS EN LA VARIABLE EXISTE*/

      SELECT COUNT(PAR.ID_PARTIDO) INTO EXISTE FROM PARTIDO PAR
      WHERE PAR.EQ_LOCAL = ID_LOCAL
      AND PAR.VISITANTE = ID_VISITANTE
      AND PAR.JORNADA_ID_JORNADA = ID_JORNADA;

      /*SI NO EXISTE EL REGISTRO ENTONCES LO CREAMOS*/

      IF EXISTE = 0 THEN
        --VICTORIA DEL LOCAL
        IF DATOS_TABLAS.GOLESLOCAL > DATOS_TABLAS.GOLESVISITA THEN

            /*Verificamos la jornada 31 de la edicion 84 en donde le quitan los puntos al almeria por impago de un jugador*/
            IF DATOS_TABLAS.JORNADA = 31 AND EDICION = 84 AND ID_LOCAL = 5  THEN
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,0,0,ID_LOCAL,ID_VISITANTE, DATOS_TABLAS.FECHA, ID_JORNADA);
            ELSE
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,PUNTOS_VICTORIA,0,ID_LOCAL,ID_VISITANTE,DATOS_TABLAS.FECHA,ID_JORNADA);
            END IF;
        --VICTORIA DEL VISITANTE
        ELSIF DATOS_TABLAS.GOLESLOCAL < DATOS_TABLAS.GOLESVISITA THEN
            /*Verificamos la edicion 49 y jornada 31 en donde se le quitan 3 puntos al salamanca por amaño de partido*/
            IF DATOS_TABLAS.JORNADA = 31 AND EDICION = 49 AND ID_VISITANTE = 55    THEN
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,0,0,ID_LOCAL,ID_VISITANTE,DATOS_TABLAS.FECHA,ID_JORNADA);
            ELSE        
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,0,PUNTOS_VICTORIA,ID_LOCAL,ID_VISITANTE,DATOS_TABLAS.FECHA,ID_JORNADA);
            END IF;
        --EMPATE
        ELSE
            /*Verificamos la jornada 16 en donde se le quita un punto al racing de santander por haber alineado simultaneamente a cuatro
            jugadores extracomunitarios en el partido contra el Osasuna*/
            IF DATOS_TABLAS.JORNADA = 16 AND EDICION = 73 AND ID_LOCAL = 47   THEN
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,-1,0,ID_LOCAL,ID_VISITANTE,DATOS_TABLAS.FECHA,ID_JORNADA);
            ELSE 
                INSERT INTO PARTIDO(GOLES_LOCAL, GOLES_VISITA, PTS_LOCAL,PTS_VISITANTE, EQ_LOCAL, VISITANTE, FECHA,JORNADA_ID_JORNADA)
                VALUES(DATOS_TABLAS.GOLESLOCAL, DATOS_TABLAS.GOLESVISITA,PUNTOS_EMPATE,PUNTOS_EMPATE,ID_LOCAL,ID_VISITANTE,DATOS_TABLAS.FECHA,ID_JORNADA);
            END IF;
        END IF;
      -- COLOCAMOS EXISTE = 0

     END IF;
     EXISTE := 0;
    END LOOP;

  END;



SELECT COUNT(PARTIDO.ID_PARTIDO) FROM PARTIDO, JORNADA, TEMPORADA where partido.jornada_id_jornada = jornada.id_jornada
AND jornada.temporada_id_temporada = temporada.id_temporada
AND temporada.edicion = 49;


select * from partido, equipo eq1, equipo eq2 where eq_local = eq1.id_equipo and partido.visitante = eq2.id_equipo and partido.fecha = '18/12/2019'
